#! /bin/bash -x

set -e

clone_url_parent=https://github.com/devexp-db/distgen.git

workdir=$(basename "$clone_url_parent")
workdir=${workdir%%.git}

hook_payload=$(readlink -f "${HOOK_PAYLOAD-hook_payload}")

# clone the helper scripts when needed, and add to PATH
test -d copr-ci-tooling \
    || git clone --depth 1 https://github.com/praiskup/copr-ci-tooling.git
export PATH="$PWD/copr-ci-tooling:$PATH"

# clone the tested project
git clone \
    --recursive \
    --no-single-branch \
    "$clone_url_parent"

# checkout requested revision
cd "$workdir"

webhook-checkout "$hook_payload"

commit=$(git rev-parse HEAD)
short_commit=${commit::5}
date=$(date +"%Y%m%d_%H%M%S")

if grep PUSH "$hook_payload"; then
    # number of commits since last tag
    git_describe=$(git describe)
    # e.g. v0.20-13-g3878fff
    IFS=- eval "set -- \$git_describe"
    RELEASE="999.git_$2_$short_commit"
else
    # we are checked out to 'pull-requests/pr/78'
    pr_branch=$(git branch -r --contains HEAD)
    IFS=/ eval "set -- \$pr_branch"
    RELEASE="PR${3}_${date}_git$short_commit"
fi

python3 -m pip install . --user
cd rpm
make RELEASE="$RELEASE"
