=== fedora-21-x86_64 ===

FROM registry.fedoraproject.org/fedora:21
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

LABEL INSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install" \
    UNINSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install"

CMD ["container-start"]


=== fedora-22-x86_64 ===

FROM registry.fedoraproject.org/fedora:22
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

LABEL INSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install" \
    UNINSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install"

CMD ["container-start"]


=== rhel-7-x86_64 ===

FROM registry.access.redhat.com/rhel7
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

LABEL INSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install" \
    UNINSTALL="docker run -t -i --rm --privileged -u 0:0 -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e LOGDIR=/var/log/\"\${NAME}\" -e DATADIR=/var/lib/\"\${NAME}\" -e CONFDIR=/etc/\"\${NAME}\" -e IMAGE=\"\${IMAGE}\" -e NAME=\"\${NAME}\" -e OPT1 -e OPT2 -e OPT3 \${OPT2} \${IMAGE} install"

CMD ["container-start"]
