#! /bin/bash

# Used by .travis.yml.

set -e
if test -n "$COPR_BUILD"; then
    curl -o copr-build https://raw.githubusercontent.com/praiskup/copr-ci-tooling/master/copr-travis-submit
    export COPR_PR_WEBHOOK="https://copr.fedorainfracloud.org/webhooks/custom/18597/341df2dc-df8d-4d15-bded-cdd23ffdd077/distgen/"
    exec bash copr-build
fi

set -x

test -n "$TRAVIS_PYTHON_VERSION"
export PYTHON="python$TRAVIS_PYTHON_VERSION"

make check \
    PYTHON="$PYTHON" \
    COVERAGE=true

make test-sdist-check \
    PYTHON="$PYTHON"

make test-git-archive-check \
    PYTHON="$PYTHON"

make test-lint

"$PYTHON" setup.py install --root "$PWD/i"
