=== fedora-21-x86_64 ===

FROM registry.fedoraproject.org/fedora:21
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]


=== fedora-22-x86_64 ===

FROM registry.fedoraproject.org/fedora:22
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]


=== rhel-7-x86_64 ===

FROM registry.access.redhat.com/rhel7
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]


=== rhel-8-x86_64 ===

FROM registry.access.redhat.com/rhel8
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]


=== rhel-9-x86_64 ===

FROM registry.access.redhat.com/rhel9
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]

=== rhel-10-x86_64 ===

FROM registry.access.redhat.com/rhel10
MAINTAINER unknown <unknown@unknown.com>

ENV container="docker"

CMD ["container-start"]

