=== fedora-20-i686 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== fedora-20-x86_64 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib64'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== fedora-21-i686 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== fedora-21-x86_64 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib64'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== fedora-22-i686 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== fedora-22-x86_64 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib64'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]


=== rhel-7-x86_64 ===

[('bindir', '/usr/bin'), ('datadir', '/usr/share'), ('docdir', '/usr/share/doc'), ('libdir', '/usr/lib64'), ('libexecdir', '/usr/libexec'), ('pkgdatadir', '/usr/share/unknown-pkg'), ('pkgdocdir', '/usr/share/doc/unknown-pkg'), ('prefix', '/usr'), ('sbindir', '/usr/sbin'), ('sysconfdir', '/etc'), ('unitdir', '/usr/lib/systemd/system'), ('userunitdir', '/usr/lib/systemd/user')]
