---
name: RPM build in Fedora Copr
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # This always runs against the default branch.  Two runs per month.
    - cron: '0 0 1,16 * *'

jobs:
  build:
    name: Submit a Copr build
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Submit the build
        env:
          COPR_PR_WEBHOOK: https://copr.fedorainfracloud.org/webhooks/custom/18597/341df2dc-df8d-4d15-bded-cdd23ffdd077/distgen/
          COPR_PUSH_WEBHOOK: ${{ secrets.COPR_PUSH_WEBHOOK }}
        run: |
          curl https://raw.githubusercontent.com/praiskup/copr-ci-tooling/main/copr-gh-actions-submit > submit
          bash submit ${{ github.event.pull_request.number }}
