=== fedora-21-i686 ===

Basic yum commands:
-------------------
yum -y install PKG
yum -y reinstall PKG
yum -y clean all --enablerepo='*'
yum -y remove a b

Docs test:
----------
yum -y install PKG
yum -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
yum install PKG
yum -y install PKG


=== fedora-21-x86_64 ===

Basic yum commands:
-------------------
yum -y install PKG
yum -y reinstall PKG
yum -y clean all --enablerepo='*'
yum -y remove a b

Docs test:
----------
yum -y install PKG
yum -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
yum install PKG
yum -y install PKG


=== fedora-22-i686 ===

Basic yum commands:
-------------------
dnf -y install PKG
dnf -y reinstall PKG
dnf -y clean all --enablerepo='*'
dnf -y remove a b

Docs test:
----------
dnf -y install PKG
dnf -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
dnf install PKG
dnf -y install PKG


=== fedora-22-x86_64 ===

Basic yum commands:
-------------------
dnf -y install PKG
dnf -y reinstall PKG
dnf -y clean all --enablerepo='*'
dnf -y remove a b

Docs test:
----------
dnf -y install PKG
dnf -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
dnf install PKG
dnf -y install PKG


=== fedora-23-i686 ===

Basic yum commands:
-------------------
dnf -y install PKG
dnf -y reinstall PKG
dnf -y clean all --enablerepo='*'
dnf -y remove a b

Docs test:
----------
dnf -y install PKG
dnf -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
dnf install PKG
dnf -y install PKG


=== fedora-23-x86_64 ===

Basic yum commands:
-------------------
dnf -y install PKG
dnf -y reinstall PKG
dnf -y clean all --enablerepo='*'
dnf -y remove a b

Docs test:
----------
dnf -y install PKG
dnf -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
dnf install PKG
dnf -y install PKG


=== rhel-7-x86_64 ===

Basic yum commands:
-------------------
yum -y install PKG
yum -y reinstall PKG
yum -y clean all --enablerepo='*'
yum -y remove a b

Docs test:
----------
yum -y install PKG
yum -y --setopt=tsflags=nodocs install PKG

Interactive test:
-----------------
yum install PKG
yum -y install PKG
